//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Egitimlerim
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Alt_Baslik { get; set; }
        public string Alt_Baslik2 { get; set; }
        public string Gno { get; set; }
        public string Tarih { get; set; }
    }
}
